title: My WildCat Studios Portfolio
description: >-
         This is my portfolio showcasing my projects and skills. 
baseurl: "" 
url: "https://vc1498502.github.io"
theme: jekyll-theme-time-machine 
